## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MathematicalSystems"); Pkg.clone("https://github.com/JuliaReach/LazySets.jl"); Pkg.test("MathematicalSystems"; coverage=true)'

after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("MathematicalSystems")); include(joinpath("docs", "make.jl"))'
  # code coverage (for both Coveralls and Codecov)
  - julia -e 'Pkg.add("Coverage")'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("MathematicalSystems")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("MathematicalSystems")); using Coverage; Codecov.submit(Codecov.process_folder())'
